### ISSUE TITLE
Error Codes with the new ProjectX file

### ISSUE THREAD

**Issue by Konvikt** [naaax123/Python-CSGO-Cheat#27]
2021-03-30 08:12:22,240 - pymem - DEBUG - Process 40864 is being debugged
2021-03-30 08:12:22,667 - pymem - DEBUG - Process 40864 is being debugged
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\James\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pymem\__init__.py", line 959, in write_float
    pymem.memory.write_float(self.process_handle, address, value)
  File "C:\Users\James\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pymem\memory.py", line 826, in write_float
    res = write_bytes(handle, address, value, length)
  File "C:\Users\James\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pymem\memory.py", line 588, in write_bytes
    raise pymem.exception.WinAPIError(error_code)
pymem.exception.WinAPIError: Windows api error, error_code: 87

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\James\Documents\CSGO-Side\Revolutionary\ProjectX.py", line 575, in main
    pm.write_float( glow_manager + entity_glow * 0x38 + 0x4, float( r ) )  # R
  File "C:\Users\James\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pymem\__init__.py", line 961, in write_float
    raise pymem.exception.MemoryWriteError(address, value, e.error_code)
pymem.exception.MemoryWriteError: Could not write memory at: -1970514780, length: 0.0 - GetLastError: 87

**Comment by Konvikt** [comment]
I should let you know that this has happened every time I've launched the program,

**Comment by naaax123** [comment]
Do you have any specific cheat (wh, aimbot...) enabled?

**Comment by Konvikt** [comment]
> Do you have any specific cheat (wh, aimbot...) enabled?

I enabled walls, aimbot, and bunnyhop. 

I assume it has something to do with wh because I get a glow error at the end.

**Comment by naaax123** [comment]
Yeah i saw that to. Maybe you could try just using aimbot and bhop or something?

The Error says a invalid parameter has been passed, which doesnt make that much sense to me as everything is still working fine for me. 
You could try to change the "float(r)" part to something like 255.0 and try again
Or you could try these troubleshooters: https://answers.microsoft.com/en-us/windows/forum/apps_windows_10-winapps-appscat_productivity/system-error-code-87-the-parameter-is-incorrect-os/734ffe3b-3730-4716-8d28-f6f3bd20627c

And did you run the file as admin? That could also fix it.

**Comment by naaax123** [comment]
I even ran it with python 3.9 and it still worked. The other obvious thing you could do is to
1. Restart your game (if you havent done that already)
2. Restart Your PC

**Comment by naaax123** [comment]
This video also might help with your problem (it seems to have to do something with you pc and not my code btw): https://www.youtube.com/watch?v=VtrT--6YwLI&ab_channel=TechinPost

**Comment by Konvikt** [comment]
> This video also might help with your problem (it seems to have to do something with you pc and not my code btw): https://www.youtube.com/watch?v=VtrT--6YwLI&ab_channel=TechinPost

So I decided the best option was to do this first, before changing the float. This fixed it, and I appreciate the swift responses. Awesome dev 👍
