### ISSUE TITLE
It doesn't work anymore...

### ISSUE THREAD

**Issue by OskarGER05** [naaax123/Python-CSGO-Cheat#37]
Idk why it isnt working anymore

**Comment by BinkBoinkBonk** [comment]
In the code there should be a var called "offsets". You need to change the current link from "https://raw.githubusercontent.com/naaax123/Python-CSGO-Cheat/main/offsets/offsets.json" to "https://raw.githubusercontent.com/frk1/hazedumper/master/csgo.json". The reason it stop working is that CSGO updated their offsets and this hack hasn't updated to the newest offsets. The link I provided is always is updated.

**Comment by OskarGER05** [comment]
Ok thanks, i will try that

**Comment by OskarGER05** [comment]
I get this error everytime:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\pymem\__init__.py", line 959, in write_float
    pymem.memory.write_float(self.process_handle, address, value)
  File "C:\Python39\lib\site-packages\pymem\memory.py", line 826, in write_float
    res = write_bytes(handle, address, value, length)
  File "C:\Python39\lib\site-packages\pymem\memory.py", line 588, in write_bytes
    raise pymem.exception.WinAPIError(error_code)
pymem.exception.WinAPIError: Windows api error, error_code: 87

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Downloads\Python-CSGO-Cheat-main\.Cheat CSGO main\ProjectX.py", line 551, in main
    pm.write_float( glow_manager + entity_glow * 0x38 + 0x4, float( r ) )  # R
  File "C:\Python39\lib\site-packages\pymem\__init__.py", line 961, in write_float
    raise pymem.exception.MemoryWriteError(address, value, e.error_code)
pymem.exception.MemoryWriteError: Could not write memory at: -1923476004, length: 0.0 - GetLastError: 87

**Comment by naaax123** [comment]
1. Pls dont change the offset link (they dont have all needed offsets)
2. Im updateing rn

**Comment by naaax123** [comment]
Working again

**Comment by OskarGER05** [comment]
Thank you very much

**Comment by OskarGER05** [comment]
It has been fixed
